; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
name = O4 Robot
description = PlatformIO project for O4 Robot
default_envs = arduino

[env]
test_framework = googletest

[env:arduino]
build_type = release
platform = atmelavr
board = uno
framework = arduino
lib_deps =
    arduino-libraries/Servo@^1.2.2
    wayoda/LedControl@^1.0.6
    https://github.com/verdi8/b-code-interpreter.git#feature/init
monitor_speed = 9600
test_ignore = *

[env:native]
build_type = test
platform = native
test_framework = googletest
test_build_src = true

